"use client";

import { useEffect, useRef, useState, type MouseEvent } from "react";
import {
  AnimatePresence,
  motion,
  useMotionValue,
  useSpring,
} from "motion/react";

import Unitedarabemirates from "@react-map/united-arab-emirates";

/* ================================================================
   BRAND LOGOS
   ================================================================ */

const brandLogos = [
  {
    name: "Dongfeng",
    type: "Automotive Brand",
    logo: "/brands/dongfeng-logo.svg",
  },
  {
    name: "OMODA | JAECOO",
    type: "Automotive Brand",
    logo: "/brands/omoda-jaecoo.svg",
  },
  {
    name: "Certified Pre-Owned",
    type: "MAHY Khooray Automotive",
    logo: "/brands/certified-pre-owned.svg",
  },
];

/* ================================================================
   UAE LOCATIONS

   Change x / y here whenever you want to move a point.

   x = horizontal position
   y = vertical position

   Both values are percentages of the 800 x 800 map.
   ================================================================ */

const locations = [
  {
    id: 1,
    x: 73.7,
    y: 33.1,
    brandIndex: 1,
  },
  {
    id: 2,
    x: 70.2,
    y: 38.4,
    brandIndex: 1,
  },
  {
    id: 3,
    x: 72.2,
    y: 38.8,
    brandIndex: 2,
  },
  {
    id: 4,
    x: 54.2,
    y: 52.2,
    brandIndex: 0,
  },
  {
    id: 5,
    x: 58.2,
    y: 52.2,
    brandIndex: 1,
  },
  {
    id: 6,
    x: 61.7,
    y: 55.5,
    brandIndex: 2,
  },
  {
    id: 7,
    x: 64.5,
    y: 53.4,
    brandIndex: 2,
  },
  {
    id: 8,
    x: 85.1,
    y: 52.5,
    brandIndex: 0,
  },
  {
    id: 9,
    x: 87.2,
    y: 52.3,
    brandIndex: 0,
  },
];

/* ================================================================
   TYPE FOR CLIP PATHS
   ================================================================ */

type MapPath = {
  d: string;
  transform?: string;
};

/* ================================================================
   HERO
   ================================================================ */

export default function Hero() {
  const heading =
    "Connecting Global Automotive Brands with the UAE";

  const subtext =
    "We continuously embrace emerging automotive technologies, from advanced powertrains to connected mobility, ensuring our customers benefit from the latest innovations.";

  const headingWords = heading.split(" ");
  const subtextWords = subtext.split(" ");

  /* ==============================================================
     ACTIVE BRAND POINT
     ============================================================== */

  const [activeLocation, setActiveLocation] =
    useState<number | null>(null);

  /* ==============================================================
     MAP REFERENCE

     We use the actual SVG generated by @react-map to extract
     the UAE paths.

     This allows our dot pattern to use the exact UAE silhouette.
     ============================================================== */

  const mapSourceRef = useRef<HTMLDivElement>(null);

  const [mapPaths, setMapPaths] = useState<MapPath[]>([]);

  const [mapViewBox, setMapViewBox] =
    useState("0 0 800 800");

  /* ==============================================================
     MOUSE POSITION

     Values are percentages inside the map stage.
     ============================================================== */

  const mouseX = useMotionValue(50);
  const mouseY = useMotionValue(50);

  const smoothMouseX = useSpring(mouseX, {
    stiffness: 140,
    damping: 28,
    mass: 0.45,
  });

  const smoothMouseY = useSpring(mouseY, {
    stiffness: 140,
    damping: 28,
    mass: 0.45,
  });

  /* ==============================================================
     EXTRACT THE REAL UAE SVG PATHS

     @react-map/united-arab-emirates renders SVG paths.

     We copy those paths into our own clipPath.

     This is what makes the dot pattern follow the exact UAE
     silhouette instead of using a fake polygon.
     ============================================================== */

  useEffect(() => {
    const extractMapPaths = () => {
      if (!mapSourceRef.current) return;

      const svg =
        mapSourceRef.current.querySelector("svg");

      if (!svg) return;

      /* ----------------------------------------------------------
         Get the SVG viewBox
         ---------------------------------------------------------- */

      const viewBox =
        svg.getAttribute("viewBox");

      if (viewBox) {
        setMapViewBox(viewBox);
      }

      /* ----------------------------------------------------------
         Get all map paths
         ---------------------------------------------------------- */

      const paths = Array.from(
        svg.querySelectorAll("path")
      );

      const extractedPaths: MapPath[] = paths
        .map((path) => {
          const d = path.getAttribute("d");

          if (!d) return null;

          const transform =
            path.getAttribute("transform");

          return {
            d,
            ...(transform
              ? { transform }
              : {}),
          };
        })
        .filter(
          (path): path is MapPath =>
            path !== null
        );

      setMapPaths(extractedPaths);
    };

    /*
     * The map renders asynchronously, so give React a moment
     * to finish mounting the SVG before extracting it.
     */

    const timeout = window.setTimeout(
      extractMapPaths,
      50
    );

    return () => {
      window.clearTimeout(timeout);
    };
  }, []);

  /* ==============================================================
     MOUSE MOVE
     ============================================================== */

  const handleMapMouseMove = (
    event: MouseEvent<HTMLDivElement>
  ) => {
    const rect =
      event.currentTarget.getBoundingClientRect();

    const x =
      ((event.clientX - rect.left) /
        rect.width) *
      100;

    const y =
      ((event.clientY - rect.top) /
        rect.height) *
      100;

    mouseX.set(x);
    mouseY.set(y);
  };

  /* ==============================================================
     MOUSE LEAVE

     Move the light outside the visible area so the dots return
     to their normal state.
     ============================================================== */

  const handleMapMouseLeave = () => {
    mouseX.set(-100);
    mouseY.set(-100);
  };

  return (
    <section className="w-full">
      <div
        className="
          mx-auto
          flex
          w-full
          max-w-[1600px]
          flex-col
          items-center
          gap-12
          px-6
          py-16
          md:min-h-[680px]
          md:flex-row
          md:items-center
          md:gap-2
          md:px-8
          md:py-10
        "
      >
        {/* ==========================================================
            LEFT CONTENT
            ========================================================== */}

        <div
          className="
            flex
            w-full
            flex-col
            gap-8
            md:max-w-[630px]
            md:shrink-0
          "
        >
          {/* ========================================================
              HEADING
              ======================================================== */}

          <motion.h1
            initial="hidden"
            animate="visible"
            className="
              max-w-[615px]
              text-3xl
              leading-[1.05]
              uppercase
              sm:text-5xl
            "
          >
            {headingWords.map((word, index) => (
              <motion.span
                key={index}
                variants={{
                  hidden: {
                    opacity: 0,
                    filter: "blur(8px)",
                    y: 8,
                  },
                  visible: {
                    opacity: 1,
                    filter: "blur(0px)",
                    y: 0,
                  },
                }}
                transition={{
                  duration: 0.7,
                  delay: index * 0.06,
                  ease: [0.22, 1, 0.36, 1],
                }}
                className="mr-[0.25em] inline-block"
              >
                {word}
              </motion.span>
            ))}
          </motion.h1>

          {/* ========================================================
              SUBTEXT
              ======================================================== */}

          <motion.p
            initial="hidden"
            animate="visible"
            className="
              max-w-[380px]
              text-lg
              leading-relaxed
              sm:text-base
              md:text-md
            "
          >
            {subtextWords.map((word, index) => (
              <motion.span
                key={index}
                variants={{
                  hidden: {
                    opacity: 0,
                    filter: "blur(8px)",
                    y: 8,
                  },
                  visible: {
                    opacity: 1,
                    filter: "blur(0px)",
                    y: 0,
                  },
                }}
                transition={{
                  duration: 0.6,
                  delay:
                    0.55 +
                    index * 0.025,
                  ease: [0.22, 1, 0.36, 1],
                }}
                className="mr-[0.25em] inline-block"
              >
                {word}
              </motion.span>
            ))}
          </motion.p>
        </div>

        {/* ==========================================================
            RIGHT MAP
            ========================================================== */}

        <div
          className="
            flex
            w-full
            items-center
            justify-center
            md:w-[68%]
            md:scale-125
          "
        >
          {/* ========================================================
              MAP INTERACTION STAGE

              The mouse listener belongs to the entire stage,
              NOT the map.

              Therefore:
              - background reacts
              - map cannot be clicked
              - map regions do not steal hover
              ======================================================== */}

          <div
            onMouseMove={handleMapMouseMove}
            onMouseLeave={handleMapMouseLeave}
            className="
              relative
              aspect-square
              w-full
              max-w-[850px]
              overflow-visible
            "
          >
            {/* ======================================================
                ======================================================
                DOT PATTERN + CURSOR LIGHT

                IMPORTANT:

                These are clipped using the ACTUAL UAE SVG paths.

                So dots cannot appear outside the UAE.
                ======================================================
                ====================================================== */}

            <svg
              viewBox={mapViewBox}
              preserveAspectRatio="xMidYMid meet"
              className="
                pointer-events-none
                absolute
                inset-0
                z-0
                h-full
                w-full
                overflow-visible
              "
            >
              {/* ====================================================
                  DEFINITIONS
                  ==================================================== */}

              <defs>
                {/* --------------------------------------------------
                    UAE CLIP PATH
                    -------------------------------------------------- */}

                <clipPath
                  id="uae-map-clip"
                  clipPathUnits="userSpaceOnUse"
                >
                  {mapPaths.map(
                    (path, index) => (
                      <path
                        key={index}
                        d={path.d}
                        transform={
                          path.transform
                        }
                      />
                    )
                  )}
                </clipPath>

                {/* --------------------------------------------------
                    DOT PATTERN
                    -------------------------------------------------- */}

                <pattern
                  id="uae-dot-pattern"
                  width="22"
                  height="22"
                  patternUnits="userSpaceOnUse"
                >
                  <circle
                    cx="3"
                    cy="3"
                    r="1.15"
                    fill="rgba(255,255,255,0.18)"
                  />
                </pattern>

                {/* --------------------------------------------------
                    CURSOR RADIAL LIGHT

                    This follows the Motion spring.
                    -------------------------------------------------- */}

                <radialGradient
                  id="uae-cursor-glow"
                  cx={`${smoothMouseX.get()}%`}
                  cy={`${smoothMouseY.get()}%`}
                  r="24%"
                >
                  <stop
                    offset="0%"
                    stopColor="rgba(255,255,255,0.32)"
                  />

                  <stop
                    offset="25%"
                    stopColor="rgba(255,255,255,0.16)"
                  />

                  <stop
                    offset="55%"
                    stopColor="rgba(255,255,255,0.05)"
                  />

                  <stop
                    offset="100%"
                    stopColor="rgba(255,255,255,0)"
                  />
                </radialGradient>
              </defs>

              {/* ====================================================
                  BASE DOTS

                  Entire rectangle is clipped to UAE.
                  ==================================================== */}

              <rect
                x="0"
                y="0"
                width="100%"
                height="100%"
                fill="url(#uae-dot-pattern)"
                clipPath="url(#uae-map-clip)"
              />

              {/* ====================================================
                  CURSOR GLOW

                  Also clipped to UAE.
                  ==================================================== */}

              <rect
                x="0"
                y="0"
                width="100%"
                height="100%"
                fill="url(#uae-cursor-glow)"
                clipPath="url(#uae-map-clip)"
              />
            </svg>

            {/* ======================================================
                SOFT AMBIENT UAE GLOW
                ====================================================== */}

            <motion.div
              className="
                pointer-events-none
                absolute
                inset-[8%]
                z-[1]
                rounded-full
                bg-[#00004D]/20
                blur-[100px]
              "
              animate={{
                scale: [1, 0.95, 1],
                opacity: [
                  0.25,
                  0.4,
                  0.25,
                ],
              }}
              transition={{
                duration: 6,
                repeat: Infinity,
                ease: "easeInOut",
              }}
            />

            {/* ======================================================
                ACTUAL MAP

                This is purely visual.

                pointer-events-none means clicking or hovering
                the UAE regions does NOTHING.
                ====================================================== */}

            <div
              ref={mapSourceRef}
              className="
                pointer-events-none
                absolute
                left-1/2
                top-1/2
                z-10
                h-[800px]
                w-[800px]
                -translate-x-1/2
                -translate-y-1/2
                scale-[0.48]
                sm:scale-[0.60]
                md:scale-[0.78]
                lg:scale-[0.88]
                xl:scale-[0.96]
              "
            >
              <div className="absolute inset-0 flex items-center justify-center">
                <Unitedarabemirates
                  type="select-single"
                  size={800}
                  mapColor="#00004D"
                  strokeColor="rgba(255,255,255,0.20)"
                  strokeWidth={1}
                  hoverColor="#00004D"
                  hints={false}
                />
              </div>
            </div>

            {/* ======================================================
                INTERACTIVE POINT LAYER

                Same coordinate system as your map.
                ====================================================== */}

            <div
              className="
                absolute
                left-1/2
                top-1/2
                z-30
                h-[800px]
                w-[800px]
                -translate-x-1/2
                -translate-y-1/2
                scale-[0.48]
                sm:scale-[0.60]
                md:scale-[0.78]
                lg:scale-[0.88]
                xl:scale-[0.96]
              "
            >
              {locations.map((location) => {
                const brand =
                  brandLogos[
                    location.brandIndex
                  ];

                const isActive =
                  activeLocation ===
                  location.id;

                return (
                  <div
                    key={location.id}
                    className="
                      absolute
                      z-30
                    "
                    style={{
                      left: `${location.x}%`,
                      top: `${location.y}%`,
                    }}
                  >
                    {/* ==================================================
                        TOOLTIP
                        ================================================== */}

                    <AnimatePresence>
                      {isActive && (
                        <motion.div
                          initial={{
                            opacity: 0,
                            y: 18,
                            scale: 0.9,
                            filter:
                              "blur(10px)",
                          }}
                          animate={{
                            opacity: 1,
                            y: 0,
                            scale: 1,
                            filter:
                              "blur(0px)",
                          }}
                          exit={{
                            opacity: 0,
                            y: 10,
                            scale: 0.94,
                            filter:
                              "blur(8px)",
                          }}
                          transition={{
                            duration: 0.4,
                            ease: [
                              0.22,
                              1,
                              0.36,
                              1,
                            ],
                          }}
                          className="
                            pointer-events-none
                            absolute
                            bottom-[58px]
                            left-1/2
                            z-[100]
                            w-[270px]
                            -translate-x-1/2
                          "
                        >
                          <div
                            className="
                              relative
                              rounded-md
                              border
                              border-white/15
                              bg-[#00004D]/95
                              px-6
                              py-5
                              shadow-[0_20px_80px_rgba(0,0,0,0.5)]
                              backdrop-blur-xl
                            "
                          >
                            {/* Top accent */}

                            <motion.div
                              initial={{
                                width: 0,
                                opacity: 0,
                              }}
                              animate={{
                                width: 38,
                                opacity: 1,
                              }}
                              transition={{
                                delay: 0.08,
                                duration: 0.3,
                              }}
                              className="
                                mb-6
                                h-[2px]
                                bg-white
                              "
                            />

                            {/* Logo */}

                            <motion.div
                              initial={{
                                opacity: 0,
                                y: 10,
                                scale: 0.85,
                              }}
                              animate={{
                                opacity: 1,
                                y: 0,
                                scale: 1,
                              }}
                              transition={{
                                delay: 0.12,
                                duration: 0.45,
                                ease: [
                                  0.22,
                                  1,
                                  0.36,
                                  1,
                                ],
                              }}
                              className="
                                flex
                                min-h-[60px]
                                w-full
                                items-center
                                justify-center
                              "
                            >
                              <img
                                src={
                                  brand.logo
                                }
                                alt={
                                  brand.name
                                }
                                draggable={
                                  false
                                }
                                className="
                                  block
                                  h-auto
                                  max-h-[60px]
                                  w-auto
                                  max-w-[210px]
                                  object-contain
                                "
                              />
                            </motion.div>

                            {/* Bottom line */}

                            <motion.div
                              initial={{
                                scaleX: 0,
                                opacity: 0,
                              }}
                              animate={{
                                scaleX: 1,
                                opacity: 1,
                              }}
                              transition={{
                                delay: 0.2,
                                duration: 0.4,
                              }}
                              className="
                                mt-5
                                h-px
                                w-full
                                origin-left
                                bg-white/10
                              "
                            />
                          </div>

                          {/* Tooltip pointer */}

                          <motion.div
                            initial={{
                              opacity: 0,
                              scale: 0,
                            }}
                            animate={{
                              opacity: 1,
                              scale: 1,
                            }}
                            exit={{
                              opacity: 0,
                              scale: 0,
                            }}
                            transition={{
                              duration: 0.2,
                            }}
                            className="
                              absolute
                              bottom-[-5px]
                              left-1/2
                              h-3
                              w-3
                              -translate-x-1/2
                              rotate-45
                              border-b
                              border-r
                              border-white/15
                              bg-[#00004D]
                            "
                          />
                        </motion.div>
                      )}
                    </AnimatePresence>

                    {/* ==================================================
                        INTERACTIVE POINT
                        ================================================== */}

                    <button
                      type="button"
                      aria-label={`View ${brand.name}`}
                      onMouseEnter={() =>
                        setActiveLocation(
                          location.id
                        )
                      }
                      onMouseLeave={() =>
                        setActiveLocation(
                          null
                        )
                      }
                      onFocus={() =>
                        setActiveLocation(
                          location.id
                        )
                      }
                      onBlur={() =>
                        setActiveLocation(
                          null
                        )
                      }
                      onClick={() =>
                        setActiveLocation(
                          isActive
                            ? null
                            : location.id
                        )
                      }
                      className="
                        group
                        relative
                        flex
                        h-12
                        w-12
                        -translate-x-1/2
                        -translate-y-1/2
                        items-center
                        justify-center
                        rounded-full
                        outline-none
                      "
                    >
                      {/* =================================================
                          OUTER BLINK
                          ================================================= */}

                      <motion.span
                        className="
                          absolute
                          h-12
                          w-12
                          rounded-full
                          border
                          border-white/40
                        "
                        animate={{
                          scale: [
                            1,
                            1.8,
                            1,
                          ],
                          opacity: [
                            0.7,
                            0,
                            0.7,
                          ],
                        }}
                        transition={{
                          duration: 2,
                          repeat: Infinity,
                          ease: "easeOut",
                        }}
                      />

                      {/* =================================================
                          SECOND PULSE
                          ================================================= */}

                      <motion.span
                        className="
                          absolute
                          h-9
                          w-9
                          rounded-full
                          border
                          border-white/30
                        "
                        animate={{
                          scale: [
                            1,
                            1.45,
                            1,
                          ],
                          opacity: [
                            0.5,
                            0,
                            0.5,
                          ],
                        }}
                        transition={{
                          duration: 2,
                          repeat: Infinity,
                          delay: 0.25,
                          ease: "easeOut",
                        }}
                      />

                      {/* =================================================
                          GLOW
                          ================================================= */}

                      <motion.span
                        className="
                          absolute
                          h-8
                          w-8
                          rounded-full
                          bg-white/30
                          blur-lg
                        "
                        animate={{
                          scale: isActive
                            ? [
                                1.3,
                                2,
                                1.3,
                              ]
                            : [
                                1,
                                1.5,
                                1,
                              ],
                          }}
                          transition={{
                            duration: 1.5,
                            repeat: Infinity,
                            ease: "easeInOut",
                          }}
                        />

                      {/* =================================================
                          CORE
                          ================================================= */}

                      <motion.span
                        className="
                          relative
                          z-10
                          h-5
                          w-5
                          rounded-full
                          border-[3px]
                          border-[#020229]
                          bg-white
                          shadow-[0_0_20px_rgba(255,255,255,0.95)]
                        "
                        animate={{
                          scale: isActive
                            ? [
                                1,
                                1.2,
                                1,
                              ]
                            : [
                                1,
                                1.08,
                                1,
                              ],
                        }}
                        transition={{
                          duration: isActive
                            ? 0.7
                            : 1.8,
                          repeat: Infinity,
                          ease: "easeInOut",
                        }}
                      />

                      {/* =================================================
                          INNER DOT
                          ================================================= */}

                      <span
                        className="
                          absolute
                          z-20
                          h-2
                          w-2
                          rounded-full
                          bg-[#00004D]
                        "
                      />
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}